import { ViewListIcon } from "@heroicons/react/solid";

const obj = {
  title: "Etsy Description",
  desc: "Quickly create an Etsy description for a product listing base on some basic details, like product, materials, etc.",
  category: "Etsy",
  Icon: ViewListIcon,
  // tags: [],
  permissions: ["user"],

  fromColor: "gray-500",
  toColor: "gray-500",

  to: "/ai/etsy/description",
  api: "/ai/etsy/description",

  output: {
    title: "Description",
    desc: "The following description generated",
    Icon: false,
    color: "orange",
  },

  prompts: [
    {
      title: "Entry Text",
      desc: "A sentence or paragraph you wish to understand in bullet point form.",
      // n: 1,
      prompts: [
        {
          title: "Describe your Product",
          attr: "product",
          value: "",
          placeholder: "D&D Dice Box",
          label:
            "Examples: Silver Bracelet, Cute Cartoon Stickers, Flower Watercolor Painting",
          // type: "textarea",
          maxLength: 40,
          // max: 100,
          min: 10,
          required: true,
          error: "",
          example: "silver bracelet with turquoise charms",
        },
        {
          title: "Type of Material",
          attr: "material",
          value: "",
          placeholder: "Walnut with maple inlays",
          label: "Examples: mahogany, walnut, maple",
          // type: "textarea",
          maxLength: 30,
          // max: 100,
          min: 3,
          required: true,
          error: "",
          example: "silver, turquoise stones",
        },
        {
          title: "Holiday",
          type: "radio",
          options: [
            { title: "Christmas", value: "Christmas" },
            { title: "Cinco de Mayo", value: "Cinco de Mayo" },
            { title: "Diwali", value: "Diwali" },
            { title: "Easter", value: "Easter" },
            { title: "Eid", value: "Eid" },
            { title: "Father's Day", value: "Father's day" },
            { title: "Halloween", value: "Halloween" },
            { title: "Hanukka", value: "Hanukka" },
            { title: "Holi", value: "Holi" },
            { title: "Independence Day", value: "Independence day" },
            { title: "Kwanzaa", value: "Kwanzaa" },
            { title: "Lunar New Year", value: "Lunar New Year" },
            { title: "Mother's Day", value: "Mother's day" },
            { title: "New Year's", value: "New Year's" },
            { title: "Passover", value: "Passover" },
            { title: "St Patrick's Day", value: "St Patrick's day" },
            { title: "Thanksgiving", value: "Thanksgiving" },
            { title: "Valentine's Day", value: "Valentine's day" },
            { title: "Veterans Day", value: "Veterans day" },
          ],
          attr: "holiday",
          value: "",
          // placeholder: "Game Nights, Role Playing",
          // label: "Examples: Christmas, Baby Shower, Fall Decor, Game Night",
          // type: "textarea",
          // maxLength: 600,
          // max: 100,
          // min: 1,
          // required: true,
          error: "",
          example: "Christmas",
        },
        {
          title: "Occasion",
          type: "radio",
          options: [
            { title: "1st Birthday", value: "1st Birthday" },
            { title: "Anniversary", value: "Anniversary" },
            { title: "Baby shower", value: "Baby shower" },
            { title: "Bachelor party", value: "Bachelor party" },
            { title: "Bachelorette party", value: "Bachelorette party" },
            { title: "Back to school", value: "Back to school" },
            { title: "Baptism", value: "Baptism" },
            { title: "Bar & Bat Mitzvah", value: "Bar & Bat Mitzvah" },
            { title: "Birthday", value: "Birthday" },
            { title: "Bridal shower", value: "Bridal shower" },
            { title: "Confirmation", value: "Confirmation" },
            { title: "Divorce & breakup", value: "Divorce & breakup" },
            { title: "Engagement", value: "Engagement" },
            { title: "First Communion", value: "First Communion" },
            { title: "Graduation", value: "Graduation" },
            { title: "Greif & mourning", value: "Greif & mourning" },
            { title: "Housewarming", value: "Housewarming" },
            { title: "LGBTQ pride", value: "LGBTQ pride" },
            { title: "Moving", value: "Moving" },
            { title: "Pet loss", value: "Pet loss" },
            { title: "Retirement", value: "Retirement" },
            { title: "Wedding", value: "Wedding" },
          ],
          attr: "occasion",
          value: "",
          // placeholder: "Game Nights, Role Playing",
          // label: "Examples: Christmas, Baby Shower, Fall Decor, Game Night",
          // type: "textarea",
          // maxLength: 600,
          // max: 100,
          // min: 1,
          // required: true,
          error: "",
          example: "Anniversary",
        },
        // {
        // 		title: "Tell us a bit about it",
        // 		attr: "content",
        // 		value: "",
        // 		placeholder: "When doing an your taxes, it's important to...",
        // 		label: "",
        // 		type: "textarea",
        // 		maxLength: 600,
        // 		// max: 100,
        // 		min: 3,
        // 		required: true,
        // 		error: "",
        // 		example: "",
        // 	},
      ],
      example: {
        output: "This beautiful, handmade silver bracelet with turquoise charms is the perfect gift for any anniversary during Christmas. The bracelet is made from sterling silver, and features two exquisite turquoise stones that add a touch of elegance and style. The unique design of this bracelet will make it an unforgettable and cherished piece for years to come. Give your special someone a beautiful reminder of your love this Christmas with this stunning silver bracelet with turquoise charms.",
        // outputs: [
        // 	"The sun is very old, over 4.5 billion years",
        // 	"At 10,000 degrees, sun is also very hot",
        // 	"Gasses called coronal mass ejections erupt from the sun",
        // ],
        // Icon: RefreshIcon,
        color: "blue",
      },
    },
  ],
};

export default obj;
